import Motak

af_da :: Af -> Bool
af_da af = ...

lengoaiakoa_da :: Af -> Hitza -> Bool
lengoaiakoa_da af hitza = ...

sailkatu :: Af -> Af_motak
sailkatu af = ...

afed_bat_lortu :: Af -> Af
afed_bat_lortu af = ...

bitarra_da :: Af -> Bool
bitarra_da af = ...

beta_afed_bat_lortu :: Af -> Af
beta_afed_bat_lortu af = ...
