kateluzapena1 : fkateak.o kateluzapena.o
	$(CC) -o $@ $+

fkateak.o : fkateak.c
	$(CC) -I /home/emmam/ikasi/azterketaAdib/include/ -o $@ -c $+

kateluzapena.o : kateluzapena.c
	$(CC) -I /home/emmam/ikasi/azterketaAdib/include/ -o $@ -c $+

clean:
	rm *.o

install:
	/home/emmam/ikasi/azterketaAdib/bin
